# Docker compos do banco de dados em MYSQL
services:
  db-cursos-online:
    image: mysql:latest
    container_name: bd-cursos-online
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursos_online
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      cursos-online-network:
        ipv4_address: 172.25.0.3

networks:
  cursos-online-network:
    name: "cursos-online-network"
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

