# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: bd-cursos-online
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.115

networks:
  macvlan_net:
    name: "macvlan-net"
    external: true