name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Obtençao do Codigo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 #   - name: Build the Docker image
 #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: . 
        file: .
        push: true
        tags: |
          joaoprdo/cursos-online:v${{github.run_number}}
          joaoprdo/cursos-online:latest