# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python



name: CI Teste python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: obtendo código
      uses: actions/checkout@v4
    - name: Configurando Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalaçao das Flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8  
    - name: Executando flake8
      # Executa o Flake8 em todo o repositório.
      run: |
        flake8 . --max-line-length=100 --ignore=E203,W503
    - name: Instalaçao das dependecias do projeto
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Teste com pytest
      run: |
        pytest
